# Generated by Django 4.0.3 on 2022-04-03 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_topic_room_host_message_room_topic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['-updated', '-created']},
        ),
    ]
